### ISSUE TITLE
Todo list

### ISSUE THREAD

**Issue by kokonut27** [kokonut27/ReplitTD#2]
* [ ] Finish up guest mode
* [ ] Add online mode using socket io
* [ ] Polish up code
